In [1]:
import torch
x = torch.randn(4, requires_grad=True)
print('x=',x)
y=torch.randn(4)
print('y=',y)
z = x + 2
print('z=',z)
t=y+2
print('t=',t)
print()

x1 = torch.arange(6.0)
print('x1=',x1)
x1.requires_grad_(True)
print('x1=',x1)


x= tensor([-1.9558,  0.7860, -0.3862, -0.1138], requires_grad=True)
y= tensor([-0.0342, -1.8424,  0.7454, -0.4236])
z= tensor([0.0442, 2.7860, 1.6138, 1.8862], grad_fn=<AddBackward0>)
t= tensor([1.9658, 0.1576, 2.7454, 1.5764])

x1= tensor([0., 1., 2., 3., 4., 5.])
x1= tensor([0., 1., 2., 3., 4., 5.], requires_grad=True)


In [2]:
import torch
x = torch.arange(6.0)
x.requires_grad_(True)
print('x=',x)
print('x.grad=',x.grad)
y = 2 * torch.dot(x, x)
print('y=',y)
y.backward()
print('x.grad=',x.grad)
print(x.grad == 4 * x)

print('x.grad_fn=',x.grad_fn)
print('y.grad_fn=',y.grad_fn)

x= tensor([0., 1., 2., 3., 4., 5.], requires_grad=True)
x.grad= None
y= tensor(110., grad_fn=<MulBackward0>)
x.grad= tensor([ 0.,  4.,  8., 12., 16., 20.])
tensor([True, True, True, True, True, True])
x.grad_fn= None
y.grad_fn= <MulBackward0 object at 0x7afd5d30e1a0>


In [3]:
from torch.autograd import Variable
x = Variable(torch.ones(2, 2), requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [4]:
import torch
x= torch.arange(5.0, requires_grad=True)
print('x=',x)
y = x * 8+15
print('y=',y)
print('y.shape=',y.shape)
v = torch.tensor([1.0, 1.0, 1.0,1.0,1.0], dtype=torch.float32)
y.backward(v)
print('x.grad=',x.grad)

x= tensor([0., 1., 2., 3., 4.], requires_grad=True)
y= tensor([15., 23., 31., 39., 47.], grad_fn=<AddBackward0>)
y.shape= torch.Size([5])
x.grad= tensor([8., 8., 8., 8., 8.])


In [5]:
print('.requires_grad_(False)')
a = torch.randn(2, 2,requires_grad=True)
print('a=',a)
a.requires_grad_(False)
print('a=',a)

print()
print(' .detach():')
a = torch.randn(3, 2, requires_grad=True)
print('a=',a)
b = a.detach()
print('b=',b)

print()
print('with torch.no_grad():')
a = torch.randn(5, 5, requires_grad=True)
print(a.requires_grad)
with torch.no_grad():
    print((x ** 2).requires_grad)
print(a.requires_grad)

.requires_grad_(False)
a= tensor([[0.1223, 1.5903],
        [0.6799, 0.7948]], requires_grad=True)
a= tensor([[0.1223, 1.5903],
        [0.6799, 0.7948]])

 .detach():
a= tensor([[ 0.3019, -1.0463],
        [-0.8104, -0.3468],
        [ 0.2766,  0.6722]], requires_grad=True)
b= tensor([[ 0.3019, -1.0463],
        [-0.8104, -0.3468],
        [ 0.2766,  0.6722]])

with torch.no_grad():
True
False
True


In [6]:
weights = torch.ones(4, requires_grad=True)
for epoch in range(3):
    model_output = (weights*3).sum()
    model_output.backward()
    print(weights.grad)
    with torch.no_grad():
        weights -= 0.1 * weights.grad
    weights.grad.zero_()
print(weights)
print(model_output)


tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([0.1000, 0.1000, 0.1000, 0.1000], requires_grad=True)
tensor(4.8000, grad_fn=<SumBackward0>)
